aws:
  concurrency: 25
  delay: 0
# :concurrency: 1
:pidfile: /tmp/pids/shoryuken.pid

:queues:
  - 'dev-incidents'
  #- mailers

# development:
#   concurrency: 1
# staging:
#   concurrency: 1
# production:
#   concurrency: 1



